######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 6 16:13:22 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += opengl
HEADERS += globj.h MainWindow.h sinc.h
SOURCES += globj.cpp main.cpp MainWindow.cpp sinc.cpp
